[package]
name = "moshiki"
version = "0.1.0"
edition = "2024"

[dependencies]
binggan = "0.14.2"
fnv = "1.0.7"
memchr = "2.7.5"
stacker = { version = "0.5", path = "./stacker", package = "tantivy-stacker" }

[[bench]]
name = "bench_tokenizer"
harness = false

# debug in bench profile
[profile.bench]
debug = true

