[package]
name = "moshiki"
version = "0.1.0"
edition = "2024"

[dependencies]
binggan = "0.14.2"
fnv = "1.0.7"
fst = "0.4.7"
fxhash = "0.2.1"
memchr = "2.7.5"
sstable = "0.11.1"
stacker = { version = "0.5", path = "./stacker", package = "tantivy-stacker" }
tantivy-sstable = "0.5.0"
zstd = "0.13.1"

[[bench]]
name = "bench_tokenizer"
harness = false

# debug in bench profile
[profile.bench]
debug = true
[profile.release]
debug = true

